# Generated by Django 2.2.3 on 2019-07-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact',
            new_name='contacts',
        ),
    ]
