# Generated by Django 2.2.3 on 2019-07-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190701_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.ManyToManyField(related_name='users', to='contacts.Contact'),
        ),
    ]
